include $(APPDIR)/Make.defs
ifneq ($(CONFIG_EXAMPLES_ZHAOXI_UI),)
PROGNAME = zhaoxi_ui
PRIORITY = 100
STACKSIZE = 16384
MAINSRC = src/zhaoxi_ui.c
CSRCS = src/zhaoxi_font_20.c src/zhaoxi_font_22.c src/zhaoxi_font_24.c src/zhaoxi_font_28.c
include $(APPDIR)/Application.mk
endif
